project:
  type: website

website:
  title: "CNG Onboarding Tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Tutorials"
        contents:
          - text: "STAC AWS"
            href: tutorials/stac/stac_load_e84_aws.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
