project:
  type: website

website:
  title: "CNG Onboarding Tutorials"
  repo-url: https://github.com/VorGeo/cng-onboarding
  repo-actions: [edit, source, issue]
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Tutorials"
        contents:
          - text: "STAC AWS"
            href: tutorials/stac/e84_aws
          - text: "STAC MSPC"
            href: tutorials/stac/mspc_stac   

format:
  html:
    theme:  # pandoc, default, flatly, darkly, sketchy, sandstone, cyborg, zephyr
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
