[project]
name = "CNG-tutorials"
description = "Cloud-Native Geospatial (CNG) tutorials"
authors = [{name = "Tyler Erickson", email = "tyler@vorgeo.com"}]
dependencies = ["black"]
requires-python = ">= 3.11"
version = "0.1.0"

[tool.black]
line-length = 88
target-version = ["py311", "py312"]
include = '\.pyi?$'
