services:
  tutorial-r-service:
    # image: rocker/r-ver:latest
    build: .devcontainer/tutorial_r_container/
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity