[project]
authors = ["Tyler Erickson <tyler@vorgeo.com>"]
channels = ["conda-forge"]
name = "python"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12"
ipykernel = ">=6.29.5,<7"
pystac = ">=1.12.1,<2"
